### ISSUE TITLE
error when compiling Kivy on Xcode due to pyobjus

### ISSUE THREAD

**Issue by faybak** [kivy/pyobjus#63]
when I want tu run Kivy iOS on Xcode, I have this error on target output. Please help 
thanks

" Traceback (most recent call last):
   File "/XXXXX/XXXXX/PycharmProjects/kivy-ios/prod-ios/YourApp/main.py", line 592, in <module>
   File "/XXXXXXXX/XXXXXXX/Library/Developer/CoreSimulator/Devices/FF2C200F-D939-4874-AF94-FB1E69041947/data/Containers/Bundle/Application/622F6B7C-C50F-4BAF-B2B0-6CE748527586/prod.app/lib/python3.8/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/XXXXX/XXXXXXX/Library/Developer/CoreSimulator/Devices/FF2C200F-D939-4874-AF94-FB1E69041947/data/Containers/Bundle/Application/622F6B7C-C50F-4BAF-B2B0-6CE748527586/prod.app/lib/python3.8/site-packages/kivy/app.py", line 944, in _run_prepare
     self.dispatch('on_start')
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/Users/proprietaire/PycharmProjects/kivy-ios/prod-ios/YourApp/main.py", line 131, in on_start
   File "pyobjus/pyobjus.pyx", line 740, in pyobjus.pyobjus.autoclass
   File "pyobjus/pyobjus.pyx", line 98, in pyobjus.pyobjus.MetaObjcClass.__new__
   File "pyobjus/pyobjus.pyx", line 129, in pyobjus.pyobjus.MetaObjcClass.resolve_class
 pyobjus.pyobjus.ObjcException: Unable to find class b'adSwitch'

**Comment by Julian-O** [comment]
There is a mailing list and a Discord channel to support Kivy users debugging their own systems, which should be able to help. They are linked in the [ReadMe](https://github.com/kivy/buildozer#support).
