### ISSUE TITLE
Error installing Pyobjus. super() takes at least 1 argument (0 given)

### ISSUE THREAD

**Issue by tanmald** [kivy/pyobjus#73]
Collecting git+http://github.com/kivy/pyobjus/
  Cloning http://github.com/kivy/pyobjus/ to /private/var/folders/2h/dzn2_c9x24d9mlcjtbfdb6080000gn/T/pip-req-build-iAPiXA
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: pyobjus
  Building wheel for pyobjus (PEP 517) ... error
  Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/2h/dzn2_c9x24d9mlcjtbfdb6080000gn/T/tmpPwI2JN:
  Pyobjus platform is darwin
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-2.7
  creating build/lib.macosx-10.9-x86_64-2.7/pyobjus
  copying pyobjus/dylib_manager.py -> build/lib.macosx-10.9-x86_64-2.7/pyobjus
  copying pyobjus/protocols.py -> build/lib.macosx-10.9-x86_64-2.7/pyobjus
  copying pyobjus/__init__.py -> build/lib.macosx-10.9-x86_64-2.7/pyobjus
  copying pyobjus/objc_py_types.py -> build/lib.macosx-10.9-x86_64-2.7/pyobjus
  creating build/lib.macosx-10.9-x86_64-2.7/pyobjus/consts
  copying pyobjus/consts/__init__.py -> build/lib.macosx-10.9-x86_64-2.7/pyobjus/consts
  copying pyobjus/consts/corebluetooth.py -> build/lib.macosx-10.9-x86_64-2.7/pyobjus/consts
  running build_ext
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 141, in build_wheel
      metadata_directory)
    File "/private/var/folders/2h/dzn2_c9x24d9mlcjtbfdb6080000gn/T/pip-build-env-0NBeh5/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 209, in build_wheel
      wheel_directory, config_settings)
    File "/private/var/folders/2h/dzn2_c9x24d9mlcjtbfdb6080000gn/T/pip-build-env-0NBeh5/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/2h/dzn2_c9x24d9mlcjtbfdb6080000gn/T/pip-build-env-0NBeh5/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/private/var/folders/2h/dzn2_c9x24d9mlcjtbfdb6080000gn/T/pip-build-env-0NBeh5/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 123, in <module>
      'Topic :: Software Development :: Libraries :: Application Frameworks'
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/2h/dzn2_c9x24d9mlcjtbfdb6080000gn/T/pip-build-env-0NBeh5/overlay/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
      self.run_command(cmd_name)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/2h/dzn2_c9x24d9mlcjtbfdb6080000gn/T/pip-build-env-0NBeh5/overlay/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "setup.py", line 50, in build_extensions
      super().build_extensions()
  TypeError: super() takes at least 1 argument (0 given)

**Comment by Julian-O** [comment]
This is related to Python 2 which is no longer supported. Closing as stale, but if the problem still exists please let us know.
